<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ModName>Create An Album</ModName>
    <ModFolderName>CreateAnAlbum</ModFolderName>
    <RootNamespace>Albummodelite</RootNamespace>
    <AssemblyName>com.jordanss.createanalbum</AssemblyName>
    <Version>4.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\**\*.cs" />
  </ItemGroup>
</Project>
